import { useEffect, useState } from 'react';
import { http } from '../../shared/api/http';

type Filters = { start: string; end: string; rangerId: string; incidentType: string; severity: string; conflictStatus: string };
type Group = { name: string; count: number };
type Data = { generatedAt: string; filters: object; summary: { patrols: { total: number; completed: number; active: number }; incidents: { total: number }; conflicts: { total: number; open: number; resolved: number }; responses: { total: number } }; incidents: { byType: Group[] }; conflicts: { bySeverity: Group[] } };
const emptyFilters: Filters = { start: '', end: '', rangerId: '', incidentType: '', severity: '', conflictStatus: '' };

export function AnalyticsPage() {
  const [data, setData] = useState<Data | null>(null); const [filters, setFilters] = useState<Filters>(emptyFilters); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = (active = filters) => { setLoading(true); setError(''); if (active.start && active.end && active.start > active.end) { setError('Start date must be before end date.'); setLoading(false); return; } const params = Object.fromEntries(Object.entries(active).filter(([, value]) => value)); http.get('/analytics', { params, headers: { 'x-user-role': 'MANAGER' } }).then(response => setData(response.data.data)).catch(() => setError('Unable to load analytics. Please try again.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const exportReport = async () => { const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value)); const response = await http.get('/analytics/report', { params: { ...params, format: 'pdf' }, headers: { 'x-user-role': 'MANAGER' }, responseType: 'blob' }); const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'conservation-report.pdf'; anchor.click(); URL.revokeObjectURL(url); };
  if (loading && !data) return <main className="page"><h1>Conservation Analytics</h1><p>Loading analytics...</p></main>;
  if (error && !data) return <main className="page"><h1>Conservation Analytics</h1><p role="alert">{error}</p><button className="button" onClick={() => load()}>Retry</button></main>;
  if (!data) return null; const s = data.summary;
  return <main className="page"><p className="eyebrow">Park manager</p><h1>Conservation Analytics</h1><p>Live metrics from central conservation data.</p><section className="card analytics-filters"><label>Start date<input type="date" value={filters.start} onChange={e => setFilters({ ...filters, start: e.target.value })} /></label><label>End date<input type="date" value={filters.end} onChange={e => setFilters({ ...filters, end: e.target.value })} /></label><label>Ranger ID<input placeholder="All rangers" value={filters.rangerId} onChange={e => setFilters({ ...filters, rangerId: e.target.value })} /></label><label>Incident type<select value={filters.incidentType} onChange={e => setFilters({ ...filters, incidentType: e.target.value })}><option value="">All types</option><option>SNARE</option><option>ANIMAL_CARCASS</option><option>ILLEGAL_CAMPSITE</option><option>AT_RISK_FOOTPRINTS</option><option>OTHER</option></select></label><label>Severity<select value={filters.severity} onChange={e => setFilters({ ...filters, severity: e.target.value })}><option value="">All severities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button className="button" onClick={() => load()}>Apply filters</button><button className="button" onClick={() => { setFilters(emptyFilters); load(emptyFilters); }}>Reset</button><button className="button" onClick={exportReport}>Download report</button></section>{error && <p role="alert">{error} <button onClick={() => load()}>Retry</button></p>}<section className="analytics-grid">{[['Patrols', s.patrols.total], ['Completed patrols', s.patrols.completed], ['Incidents', s.incidents.total], ['Conflict alerts', s.conflicts.total], ['Open conflicts', s.conflicts.open], ['Resolved conflicts', s.conflicts.resolved], ['Responses', s.responses.total]].map(([label, value]) => <article className="card" key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</section><section className="card"><h2>Incidents by type</h2>{data.incidents.byType.length ? <ul>{data.incidents.byType.map(x => <li key={x.name}>{x.name}: {x.count}</li>)}</ul> : <p>No incidents match the selected filters.</p>}</section><section className="card"><h2>Conflict severity</h2>{data.conflicts.bySeverity.length ? <ul>{data.conflicts.bySeverity.map(x => <li key={x.name}>{x.name}: {x.count}</li>)}</ul> : <p>No conflict alerts match the selected filters.</p>}</section></main>;
}
