export enum SyncStatus { LOCAL = 'LOCAL', PENDING = 'PENDING', SYNCING = 'SYNCING', SYNCED = 'SYNCED', FAILED = 'FAILED' }
export enum PatrolStatus { ASSIGNED = 'ASSIGNED', ACTIVE = 'ACTIVE', COMPLETED = 'COMPLETED' }
export enum LocationSource { GPS = 'GPS', MANUAL = 'MANUAL' }
export enum IncidentType {
  SNARE = 'SNARE',
  ANIMAL_CARCASS = 'ANIMAL_CARCASS',
  ILLEGAL_CAMPSITE = 'ILLEGAL_CAMPSITE',
  AT_RISK_FOOTPRINTS = 'AT_RISK_FOOTPRINTS',
  OTHER = 'OTHER'
}
export enum IncidentStatus {
  REPORTED = 'REPORTED',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED'
}

export enum AlertSource {
  COLLAR = 'COLLAR',
  COMMUNITY_REPORT = 'COMMUNITY_REPORT'
}

export enum ConflictAlertType {
  WILDLIFE_NEAR_COMMUNITY = 'WILDLIFE_NEAR_COMMUNITY',
  WILDLIFE_NEAR_RANGER = 'WILDLIFE_NEAR_RANGER',
  CROP_RAID = 'CROP_RAID',
  LIVESTOCK_THREAT = 'LIVESTOCK_THREAT',
  DANGEROUS_WILDLIFE_ACTIVITY = 'DANGEROUS_WILDLIFE_ACTIVITY',
  OTHER = 'OTHER'
}

export enum AlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum AlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESPONDING = 'RESPONDING',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED'
}

export enum ResponseAction {
  INVESTIGATED_AREA = 'INVESTIGATED_AREA',
  WARNED_COMMUNITY = 'WARNED_COMMUNITY',
  REDIRECTED_WILDLIFE = 'REDIRECTED_WILDLIFE',
  CONTACTED_MANAGEMENT = 'CONTACTED_MANAGEMENT',
  MONITORED_WILDLIFE = 'MONITORED_WILDLIFE',
  SECURED_AREA = 'SECURED_AREA',
  ESCALATED_SITUATION = 'ESCALATED_SITUATION',
  OTHER = 'OTHER'
}


